/*
 * Fatture in Cloud API v2 - API Reference
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.1.5
 * Contact: info@fattureincloud.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package it.fattureincloud.sdk.model;


import com.google.gson.JsonElement;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/** Webhooks event type */
@JsonAdapter(EventType.Adapter.class)
public enum EventType {
  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_INVOICES_CREATE(
      "it.fattureincloud.webhooks.issued_documents.invoices.create"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_INVOICES_UPDATE(
      "it.fattureincloud.webhooks.issued_documents.invoices.update"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_INVOICES_DELETE(
      "it.fattureincloud.webhooks.issued_documents.invoices.delete"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_QUOTES_CREATE(
      "it.fattureincloud.webhooks.issued_documents.quotes.create"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_QUOTES_UPDATE(
      "it.fattureincloud.webhooks.issued_documents.quotes.update"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_QUOTES_DELETE(
      "it.fattureincloud.webhooks.issued_documents.quotes.delete"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_PROFORMAS_CREATE(
      "it.fattureincloud.webhooks.issued_documents.proformas.create"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_PROFORMAS_UPDATE(
      "it.fattureincloud.webhooks.issued_documents.proformas.update"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_PROFORMAS_DELETE(
      "it.fattureincloud.webhooks.issued_documents.proformas.delete"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_RECEIPTS_CREATE(
      "it.fattureincloud.webhooks.issued_documents.receipts.create"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_RECEIPTS_UPDATE(
      "it.fattureincloud.webhooks.issued_documents.receipts.update"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_RECEIPTS_DELETE(
      "it.fattureincloud.webhooks.issued_documents.receipts.delete"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_DELIVERY_NOTES_CREATE(
      "it.fattureincloud.webhooks.issued_documents.delivery_notes.create"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_DELIVERY_NOTES_UPDATE(
      "it.fattureincloud.webhooks.issued_documents.delivery_notes.update"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_DELIVERY_NOTES_DELETE(
      "it.fattureincloud.webhooks.issued_documents.delivery_notes.delete"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_CREDIT_NOTES_CREATE(
      "it.fattureincloud.webhooks.issued_documents.credit_notes.create"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_CREDIT_NOTES_UPDATE(
      "it.fattureincloud.webhooks.issued_documents.credit_notes.update"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_CREDIT_NOTES_DELETE(
      "it.fattureincloud.webhooks.issued_documents.credit_notes.delete"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_ORDERS_CREATE(
      "it.fattureincloud.webhooks.issued_documents.orders.create"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_ORDERS_UPDATE(
      "it.fattureincloud.webhooks.issued_documents.orders.update"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_ORDERS_DELETE(
      "it.fattureincloud.webhooks.issued_documents.orders.delete"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_WORK_REPORTS_CREATE(
      "it.fattureincloud.webhooks.issued_documents.work_reports.create"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_WORK_REPORTS_UPDATE(
      "it.fattureincloud.webhooks.issued_documents.work_reports.update"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_WORK_REPORTS_DELETE(
      "it.fattureincloud.webhooks.issued_documents.work_reports.delete"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_SUPPLIER_ORDERS_CREATE(
      "it.fattureincloud.webhooks.issued_documents.supplier_orders.create"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_SUPPLIER_ORDERS_UPDATE(
      "it.fattureincloud.webhooks.issued_documents.supplier_orders.update"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_SUPPLIER_ORDERS_DELETE(
      "it.fattureincloud.webhooks.issued_documents.supplier_orders.delete"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_SELF_INVOICES_CREATE(
      "it.fattureincloud.webhooks.issued_documents.self_invoices.create"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_SELF_INVOICES_UPDATE(
      "it.fattureincloud.webhooks.issued_documents.self_invoices.update"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_SELF_INVOICES_DELETE(
      "it.fattureincloud.webhooks.issued_documents.self_invoices.delete"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_ALL_CREATE(
      "it.fattureincloud.webhooks.issued_documents.all.create"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_ALL_UPDATE(
      "it.fattureincloud.webhooks.issued_documents.all.update"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_ALL_DELETE(
      "it.fattureincloud.webhooks.issued_documents.all.delete"),

  IT_FATTUREINCLOUD_WEBHOOKS_RECEIVED_DOCUMENTS_CREATE(
      "it.fattureincloud.webhooks.received_documents.create"),

  IT_FATTUREINCLOUD_WEBHOOKS_RECEIVED_DOCUMENTS_UPDATE(
      "it.fattureincloud.webhooks.received_documents.update"),

  IT_FATTUREINCLOUD_WEBHOOKS_RECEIVED_DOCUMENTS_DELETE(
      "it.fattureincloud.webhooks.received_documents.delete"),

  IT_FATTUREINCLOUD_WEBHOOKS_RECEIPTS_CREATE("it.fattureincloud.webhooks.receipts.create"),

  IT_FATTUREINCLOUD_WEBHOOKS_RECEIPTS_UPDATE("it.fattureincloud.webhooks.receipts.update"),

  IT_FATTUREINCLOUD_WEBHOOKS_RECEIPTS_DELETE("it.fattureincloud.webhooks.receipts.delete"),

  IT_FATTUREINCLOUD_WEBHOOKS_TAXES_CREATE("it.fattureincloud.webhooks.taxes.create"),

  IT_FATTUREINCLOUD_WEBHOOKS_TAXES_UPDATE("it.fattureincloud.webhooks.taxes.update"),

  IT_FATTUREINCLOUD_WEBHOOKS_TAXES_DELETE("it.fattureincloud.webhooks.taxes.delete"),

  IT_FATTUREINCLOUD_WEBHOOKS_ARCHIVE_DOCUMENTS_CREATE(
      "it.fattureincloud.webhooks.archive_documents.create"),

  IT_FATTUREINCLOUD_WEBHOOKS_ARCHIVE_DOCUMENTS_UPDATE(
      "it.fattureincloud.webhooks.archive_documents.update"),

  IT_FATTUREINCLOUD_WEBHOOKS_ARCHIVE_DOCUMENTS_DELETE(
      "it.fattureincloud.webhooks.archive_documents.delete"),

  IT_FATTUREINCLOUD_WEBHOOKS_CASHBOOK_CREATE("it.fattureincloud.webhooks.cashbook.create"),

  IT_FATTUREINCLOUD_WEBHOOKS_CASHBOOK_UPDATE("it.fattureincloud.webhooks.cashbook.update"),

  IT_FATTUREINCLOUD_WEBHOOKS_CASHBOOK_DELETE("it.fattureincloud.webhooks.cashbook.delete"),

  IT_FATTUREINCLOUD_WEBHOOKS_PRODUCTS_CREATE("it.fattureincloud.webhooks.products.create"),

  IT_FATTUREINCLOUD_WEBHOOKS_PRODUCTS_UPDATE("it.fattureincloud.webhooks.products.update"),

  IT_FATTUREINCLOUD_WEBHOOKS_PRODUCTS_DELETE("it.fattureincloud.webhooks.products.delete"),

  IT_FATTUREINCLOUD_WEBHOOKS_PRODUCTS_STOCK_UPDATE(
      "it.fattureincloud.webhooks.products.stock_update"),

  IT_FATTUREINCLOUD_WEBHOOKS_ENTITIES_CLIENTS_CREATE(
      "it.fattureincloud.webhooks.entities.clients.create"),

  IT_FATTUREINCLOUD_WEBHOOKS_ENTITIES_CLIENTS_UPDATE(
      "it.fattureincloud.webhooks.entities.clients.update"),

  IT_FATTUREINCLOUD_WEBHOOKS_ENTITIES_CLIENTS_DELETE(
      "it.fattureincloud.webhooks.entities.clients.delete"),

  IT_FATTUREINCLOUD_WEBHOOKS_ENTITIES_SUPPLIERS_CREATE(
      "it.fattureincloud.webhooks.entities.suppliers.create"),

  IT_FATTUREINCLOUD_WEBHOOKS_ENTITIES_SUPPLIERS_UPDATE(
      "it.fattureincloud.webhooks.entities.suppliers.update"),

  IT_FATTUREINCLOUD_WEBHOOKS_ENTITIES_SUPPLIERS_DELETE(
      "it.fattureincloud.webhooks.entities.suppliers.delete"),

  IT_FATTUREINCLOUD_WEBHOOKS_ENTITIES_ALL_CREATE("it.fattureincloud.webhooks.entities.all.create"),

  IT_FATTUREINCLOUD_WEBHOOKS_ENTITIES_ALL_UPDATE("it.fattureincloud.webhooks.entities.all.update"),

  IT_FATTUREINCLOUD_WEBHOOKS_ENTITIES_ALL_DELETE("it.fattureincloud.webhooks.entities.all.delete"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_E_INVOICES_STATUS_UPDATE(
      "it.fattureincloud.webhooks.issued_documents.e_invoices.status_update"),

  IT_FATTUREINCLOUD_WEBHOOKS_RECEIVED_DOCUMENTS_E_INVOICES_RECEIVE(
      "it.fattureincloud.webhooks.received_documents.e_invoices.receive"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_INVOICES_EMAIL_SENT(
      "it.fattureincloud.webhooks.issued_documents.invoices.email_sent"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_QUOTES_EMAIL_SENT(
      "it.fattureincloud.webhooks.issued_documents.quotes.email_sent"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_PROFORMAS_EMAIL_SENT(
      "it.fattureincloud.webhooks.issued_documents.proformas.email_sent"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_RECEIPTS_EMAIL_SENT(
      "it.fattureincloud.webhooks.issued_documents.receipts.email_sent"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_DELIVERY_NOTES_EMAIL_SENT(
      "it.fattureincloud.webhooks.issued_documents.delivery_notes.email_sent"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_CREDIT_NOTES_EMAIL_SENT(
      "it.fattureincloud.webhooks.issued_documents.credit_notes.email_sent"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_ORDERS_EMAIL_SENT(
      "it.fattureincloud.webhooks.issued_documents.orders.email_sent"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_WORK_REPORTS_EMAIL_SENT(
      "it.fattureincloud.webhooks.issued_documents.work_reports.email_sent"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_SUPPLIER_ORDERS_EMAIL_SENT(
      "it.fattureincloud.webhooks.issued_documents.supplier_orders.email_sent"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_SELF_INVOICES_EMAIL_SENT(
      "it.fattureincloud.webhooks.issued_documents.self_invoices.email_sent"),

  IT_FATTUREINCLOUD_WEBHOOKS_ISSUED_DOCUMENTS_ALL_EMAIL_SENT(
      "it.fattureincloud.webhooks.issued_documents.all.email_sent");

  private String value;

  EventType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static EventType fromValue(String value) {
    for (EventType b : EventType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<EventType> {
    @Override
    public void write(final JsonWriter jsonWriter, final EventType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public EventType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return EventType.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    EventType.fromValue(value);
  }
}
