/*
 * Fatture in Cloud API v2 - API Reference
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.0.11
 * Contact: info@fattureincloud.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.fattureincloud.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import it.fattureincloud.sdk.model.IssuedDocumentTotalsVatListVatItem;
import java.io.IOException;
import java.io.Serializable;

/**
 * IssuedDocumentTotalsVatList
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-02-07T11:20:58.969Z[Etc/UTC]")
public class IssuedDocumentTotalsVatList implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_VAT_ITEM = "vat_item";
  @SerializedName(SERIALIZED_NAME_VAT_ITEM)
  private IssuedDocumentTotalsVatListVatItem vatItem;


  public IssuedDocumentTotalsVatList vatItem(IssuedDocumentTotalsVatListVatItem vatItem) {
    
    this.vatItem = vatItem;
    return this;
  }

   /**
   * Get vatItem
   * @return vatItem
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public IssuedDocumentTotalsVatListVatItem getVatItem() {
    return vatItem;
  }


  public void setVatItem(IssuedDocumentTotalsVatListVatItem vatItem) {
    this.vatItem = vatItem;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IssuedDocumentTotalsVatList issuedDocumentTotalsVatList = (IssuedDocumentTotalsVatList) o;
    return Objects.equals(this.vatItem, issuedDocumentTotalsVatList.vatItem);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vatItem);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IssuedDocumentTotalsVatList {\n");
    sb.append("    vatItem: ").append(toIndentedString(vatItem)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

