/*
 * Fatture in Cloud API v2 - API Reference
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.0.9
 * Contact: info@fattureincloud.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.fattureincloud.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import it.fattureincloud.sdk.model.ListF24ResponseAggregatedDataAggregatedData;
import java.io.IOException;
import java.io.Serializable;

/**
 * ListF24ResponseAggregatedData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-24T15:38:03.260Z[Etc/UTC]")
public class ListF24ResponseAggregatedData implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_AGGREGATED_DATA = "aggregated_data";
  @SerializedName(SERIALIZED_NAME_AGGREGATED_DATA)
  private ListF24ResponseAggregatedDataAggregatedData aggregatedData;

  public ListF24ResponseAggregatedData() { 
  }

  public ListF24ResponseAggregatedData aggregatedData(ListF24ResponseAggregatedDataAggregatedData aggregatedData) {
    
    this.aggregatedData = aggregatedData;
    return this;
  }

   /**
   * Get aggregatedData
   * @return aggregatedData
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ListF24ResponseAggregatedDataAggregatedData getAggregatedData() {
    return aggregatedData;
  }


  public void setAggregatedData(ListF24ResponseAggregatedDataAggregatedData aggregatedData) {
    this.aggregatedData = aggregatedData;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListF24ResponseAggregatedData listF24ResponseAggregatedData = (ListF24ResponseAggregatedData) o;
    return Objects.equals(this.aggregatedData, listF24ResponseAggregatedData.aggregatedData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(aggregatedData);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListF24ResponseAggregatedData {\n");
    sb.append("    aggregatedData: ").append(toIndentedString(aggregatedData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

