/*
 * Fatture in Cloud API v2 - API Reference
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.1.5
 * Contact: info@fattureincloud.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package it.fattureincloud.sdk.model;

import com.google.gson.annotations.SerializedName;
import java.io.Serializable;
import java.util.Arrays;
import java.util.Objects;
import org.openapitools.jackson.nullable.JsonNullable;

/** VerifyWebhooksSubscription */
@javax.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2025-03-06T15:40:46.627547Z[Etc/UTC]",
    comments = "Generator version: 7.12.0")
public class VerifyWebhooksSubscription implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_ID = "id";

  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_VERIFICATION_METHOD = "verification_method";

  @SerializedName(SERIALIZED_NAME_VERIFICATION_METHOD)
  private WebhooksSubscriptionVerificationMethod verificationMethod;

  public VerifyWebhooksSubscription() {}

  public VerifyWebhooksSubscription id(String id) {

    this.id = id;
    return this;
  }

  /**
   * Webhooks subscription id
   *
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public VerifyWebhooksSubscription verificationMethod(
      WebhooksSubscriptionVerificationMethod verificationMethod) {

    this.verificationMethod = verificationMethod;
    return this;
  }

  /**
   * Get verificationMethod
   *
   * @return verificationMethod
   */
  @javax.annotation.Nullable
  public WebhooksSubscriptionVerificationMethod getVerificationMethod() {
    return verificationMethod;
  }

  public void setVerificationMethod(WebhooksSubscriptionVerificationMethod verificationMethod) {
    this.verificationMethod = verificationMethod;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VerifyWebhooksSubscription verifyWebhooksSubscription = (VerifyWebhooksSubscription) o;
    return Objects.equals(this.id, verifyWebhooksSubscription.id)
        && Objects.equals(this.verificationMethod, verifyWebhooksSubscription.verificationMethod);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b
        || (a != null
            && b != null
            && a.isPresent()
            && b.isPresent()
            && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, verificationMethod);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[] {a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VerifyWebhooksSubscription {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    verificationMethod: ").append(toIndentedString(verificationMethod)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
