/*
 * Fatture in Cloud API v2 - API Reference
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.0.7
 * Contact: info@fattureincloud.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.fattureincloud.sdk.model;

import com.google.gson.Gson;
import it.fattureincloud.sdk.JSON;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;


/**
 * Model tests for CashbookEntryType
 */
public class CashbookEntryTypeTest {
    /**
     * Model tests for CashbookEntryType
     */
    @Test
    public void testCashbookEntryType() {
        JSON jsonManager = new JSON();
        Gson gson = jsonManager.getGson();

        assertEquals("\"in\"", gson.toJson(CashbookEntryType.IN));
        assertEquals("\"out\"", gson.toJson(CashbookEntryType.OUT));

        assertEquals(CashbookEntryType.IN, gson.fromJson("\"in\"", CashbookEntryType.class));
        assertEquals(CashbookEntryType.OUT, gson.fromJson("\"out\"", CashbookEntryType.class));

        assertEquals("in", CashbookEntryType.IN.getValue());
        assertEquals("out", CashbookEntryType.OUT.getValue());

        assertEquals("in", CashbookEntryType.IN.toString());
        assertEquals("out", CashbookEntryType.OUT.toString());

        assertEquals(CashbookEntryType.IN, CashbookEntryType.fromValue("in"));
        assertEquals(CashbookEntryType.OUT, CashbookEntryType.fromValue("out"));
    }

}
