/*
 * Fatture in Cloud API v2 - API Reference
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.0.27
 * Contact: info@fattureincloud.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.fattureincloud.sdk.model;

import com.google.gson.Gson;
import it.fattureincloud.sdk.JSON;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;


/**
 * Model tests for CreateWebhooksSubscriptionRequest
 */
public class CreateWebhooksSubscriptionRequestTest {
    private CreateWebhooksSubscriptionRequest model;

    @BeforeEach
    public void init() {
        ArrayList<EventType> types = new ArrayList<>();
        types.add(EventType.CASHBOOK_CREATE);
        model =
                new CreateWebhooksSubscriptionRequest()
                        .data(
                                new WebhooksSubscription()
                                        .sink("https://endpoint.test")
                                        .types(types)
                        );
    }

    /**
     * Model tests for CreateWebhooksSubscriptionRequest
     */
    @Test
    public void testCreateWebhooksSubscriptionRequest() {
        JSON jsonManager = new JSON();
        Gson gson = jsonManager.getGson();
        String json = gson.toJson(model);
        String str = "{\"data\":{\"sink\":\"https://endpoint.test\",\"types\":[\"it.fattureincloud.cashbook.create\"]}}";
        assertEquals(str, json);
        CreateWebhooksSubscriptionRequest generated = gson.fromJson(str, CreateWebhooksSubscriptionRequest.class);
        assertEquals(model, generated);

        Object o = model;
        assertEquals(model, o);
        assertFalse(model.equals(null));
        assertFalse(model.equals(Integer.getInteger("5")));
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        assertEquals("https://endpoint.test", model.getData().getSink());
        model.setData(new WebhooksSubscription().sink("https://endpoint2.test"));
        assertEquals("https://endpoint2.test", model.getData().getSink());

        model.data(new WebhooksSubscription().sink("https://endpoint3.test"));
        CreateWebhooksSubscriptionRequest actual = new CreateWebhooksSubscriptionRequest();
        actual.setData(new WebhooksSubscription().sink("https://endpoint3.test"));
        assertEquals(model, actual);
    }

}
