/*
 * Fatture in Cloud API v2 - API Reference
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.0.12
 * Contact: info@fattureincloud.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.fattureincloud.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for EntityOptions
 */
public class EntityOptionsTest {
    private final EntityOptions model = new EntityOptions();

    /**
     * Model tests for EntityOptions
     */
    @Test
    public void testEntityOptions() {
        // TODO: test EntityOptions
    }

    /**
     * Test the property 'entitySearchFields'
     */
    @Test
    public void entitySearchFieldsTest() {
        // TODO: test entitySearchFields
    }

    /**
     * Test the property 'entityAutocomplete'
     */
    @Test
    public void entityAutocompleteTest() {
        // TODO: test entityAutocomplete
    }

    /**
     * Test the property 'entityCreate'
     */
    @Test
    public void entityCreateTest() {
        // TODO: test entityCreate
    }

    /**
     * Test the property 'entityUpdate'
     */
    @Test
    public void entityUpdateTest() {
        // TODO: test entityUpdate
    }

}
