/*
 * Fatture in Cloud API v2 - API Reference
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.0.27
 * Contact: info@fattureincloud.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.fattureincloud.sdk.model;

import com.google.gson.Gson;
import it.fattureincloud.sdk.JSON;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;


/**
 * Model tests for EventType
 */
public class EventTypeTest {
    /**
     * Model tests for EventType
     */
    @Test
    public void testEventType() {
        JSON jsonManager = new JSON();
        Gson gson = jsonManager.getGson();

        assertEquals("\"it.fattureincloud.webhooks.cashbook.create\"", gson.toJson(EventType.CASHBOOK_CREATE));
        assertEquals("\"it.fattureincloud.webhooks.issued_documents.proformas.create\"", gson.toJson(EventType.ISSUED_DOCUMENTS_PROFORMAS_CREATE));
        assertEquals("\"it.fattureincloud.webhooks.issued_documents.all.create\"", gson.toJson(EventType.ISSUED_DOCUMENTS_ALL_CREATE));
        assertEquals("\"it.fattureincloud.webhooks.products.delete\"", gson.toJson(EventType.PRODUCTS_DELETE));
        assertEquals("\"it.fattureincloud.webhooks.entities.all.update\"", gson.toJson(EventType.ENTITIES_ALL_UPDATE));


        assertEquals(EventType.CASHBOOK_CREATE, gson.fromJson("\"it.fattureincloud.webhooks.cashbook.create\"", EventType.class));
        assertEquals(EventType.ISSUED_DOCUMENTS_PROFORMAS_CREATE, gson.fromJson("\"it.fattureincloud.webhooks.issued_documents.proformas.create\"", EventType.class));
        assertEquals(EventType.ISSUED_DOCUMENTS_ALL_CREATE, gson.fromJson("\"it.fattureincloud.webhooks.issued_documents.all.create\"", EventType.class));
        assertEquals(EventType.PRODUCTS_DELETE, gson.fromJson("\"it.fattureincloud.webhooks.products.delete\"", EventType.class));
        assertEquals(EventType.ENTITIES_ALL_UPDATE, gson.fromJson("\"it.fattureincloud.webhooks.entities.all.update\"", EventType.class));


        assertEquals("it.fattureincloud.webhooks.cashbook.create", EventType.CASHBOOK_CREATE.getValue());
        assertEquals("it.fattureincloud.webhooks.issued_documents.proformas.create", EventType.ISSUED_DOCUMENTS_PROFORMAS_CREATE.getValue());
        assertEquals("it.fattureincloud.webhooks.issued_documents.all.create", EventType.ISSUED_DOCUMENTS_ALL_CREATE.getValue());
        assertEquals("it.fattureincloud.webhooks.products.delete", EventType.PRODUCTS_DELETE.getValue());
        assertEquals("it.fattureincloud.webhooks.entities.all.update", EventType.ENTITIES_ALL_UPDATE.getValue());


        assertEquals("it.fattureincloud.webhooks.cashbook.create", EventType.CASHBOOK_CREATE.toString());
        assertEquals("it.fattureincloud.webhooks.issued_documents.proformas.create", EventType.ISSUED_DOCUMENTS_PROFORMAS_CREATE.toString());
        assertEquals("it.fattureincloud.webhooks.issued_documents.all.create", EventType.ISSUED_DOCUMENTS_ALL_CREATE.toString());
        assertEquals("it.fattureincloud.webhooks.products.delete", EventType.PRODUCTS_DELETE.toString());
        assertEquals("it.fattureincloud.webhooks.entities.all.update", EventType.ENTITIES_ALL_UPDATE.toString());


        assertEquals(EventType.CASHBOOK_CREATE, EventType.fromValue("it.fattureincloud.webhooks.cashbook.create"));
        assertEquals(EventType.ISSUED_DOCUMENTS_PROFORMAS_CREATE, EventType.fromValue("it.fattureincloud.webhooks.issued_documents.proformas.create"));
        assertEquals(EventType.ISSUED_DOCUMENTS_ALL_CREATE, EventType.fromValue("it.fattureincloud.webhooks.issued_documents.all.create"));
        assertEquals(EventType.PRODUCTS_DELETE, EventType.fromValue("it.fattureincloud.webhooks.products.delete"));
        assertEquals(EventType.ENTITIES_ALL_UPDATE, EventType.fromValue("it.fattureincloud.webhooks.entities.all.update"));

    }

}
