/*
 * Fatture in Cloud API v2 - API Reference
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.0.7
 * Contact: info@fattureincloud.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.fattureincloud.sdk.model;

import com.google.gson.Gson;
import it.fattureincloud.sdk.JSON;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;


/**
 * Model tests for GetPaymentMethodResponse
 */
public class GetPaymentMethodResponseTest {
    private GetPaymentMethodResponse model;

    @BeforeEach
    public void init() {
        model = new GetPaymentMethodResponse()
                .data(
                        new PaymentMethod()
                                .id(12345)
                                .name("Bonifico bancario")
                                .type(PaymentMethodType.STANDARD)
                                .isDefault(true)
                                .details(Arrays.asList(new PaymentMethodDetails()
                                        .title("t1")
                                ))
                                .defaultPaymentAccount(new PaymentAccount()
                                        .id(21)
                                        .name("n1")
                                )
                                .bankIban("IT62W0300203280486429468578")
                                .bankName("Indesa")
                                .bankBeneficiary("mamma")
                                .eiPaymentMethod("2")
                );
    }

    /**
     * Model tests for GetPaymentMethodResponse
     */
    @Test
    public void testGetPaymentMethodResponse() {
        JSON jsonManager = new JSON();
        Gson gson = jsonManager.getGson();
        String json = gson.toJson(model);
        String str = "{\"data\":{\"id\":12345,\"name\":\"Bonifico bancario\",\"type\":\"standard\",\"is_default\":true,\"default_payment_account\":{\"id\":21,\"name\":\"n1\",\"type\":\"standard\"},\"details\":[{\"title\":\"t1\"}],\"bank_iban\":\"IT62W0300203280486429468578\",\"bank_name\":\"Indesa\",\"bank_beneficiary\":\"mamma\",\"ei_payment_method\":\"2\"}}";
        assertEquals(str, json);
        GetPaymentMethodResponse generated = gson.fromJson(str, GetPaymentMethodResponse.class);
        assertEquals(model, generated);

        Object o = model;
        assertEquals(model, o);
        assertFalse(model.equals(null));
        assertFalse(model.equals(Integer.getInteger("5")));
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        assertEquals(12345, model.getData().getId());
        model.setData(new PaymentMethod().id(1));
        assertEquals(1, model.getData().getId());

        model.data(new PaymentMethod().id(2));
        GetPaymentMethodResponse actual = new GetPaymentMethodResponse();
        actual.setData(new PaymentMethod().id(2));
        assertEquals(model, actual);
    }

}
