/*
 * Fatture in Cloud API v2 - API Reference
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.1.5
 * Contact: info@fattureincloud.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.fattureincloud.sdk.model;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;

import it.fattureincloud.sdk.JSON;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PriceListPricesType
 */
public class PriceListPricesTypeTest {
    /**
     * Model tests for PriceListPricesType
     */
    @Test
    public void testPriceListPricesType() {
        JSON jsonManager = new JSON();
        Gson gson = jsonManager.getGson();

        assertEquals("\"net\"", gson.toJson(PriceListPricesType.NET));
        assertEquals("\"gross\"", gson.toJson(PriceListPricesType.GROSS));

        assertEquals(PriceListPricesType.NET, gson.fromJson("\"net\"", PriceListPricesType.class));
        assertEquals(PriceListPricesType.GROSS, gson.fromJson("\"gross\"", PriceListPricesType.class));

        assertEquals("net", PriceListPricesType.NET.getValue());
        assertEquals("gross", PriceListPricesType.GROSS.getValue());

        assertEquals("net", PriceListPricesType.NET.toString());
        assertEquals("gross", PriceListPricesType.GROSS.toString());

        assertEquals(PriceListPricesType.NET, PriceListPricesType.fromValue("net"));
        assertEquals(PriceListPricesType.GROSS, PriceListPricesType.fromValue("gross"));
    }

}
