/*
 * Fatture in Cloud API v2 - API Reference
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.0.7
 * Contact: info@fattureincloud.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.fattureincloud.sdk.model;

import com.google.gson.Gson;
import it.fattureincloud.sdk.JSON;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.math.BigDecimal;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;


/**
 * Model tests for ReceivedDocumentInfoItemsDefaultValues
 */
public class ReceivedDocumentInfoItemsDefaultValuesTest {
    private ReceivedDocumentInfoItemsDefaultValues model;

    @BeforeEach
    public void init() {
        model = new ReceivedDocumentInfoItemsDefaultValues()
                .vat(BigDecimal.valueOf(10));
    }

    /**
     * Model tests for ReceivedDocumentInfoItemsDefaultValues
     */
    @Test
    public void testReceivedDocumentInfoItemsDefaultValues() {
        JSON jsonManager = new JSON();
        Gson gson = jsonManager.getGson();
        String json = gson.toJson(model);
        String str = "{\"vat\":10}";
        assertEquals(str, json);
        ReceivedDocumentInfoItemsDefaultValues generated = gson.fromJson(str, ReceivedDocumentInfoItemsDefaultValues.class);
        assertEquals(model, generated);

        Object o = model;
        assertEquals(model, o);
        assertFalse(model.equals(null));
        assertFalse(model.equals(Integer.getInteger("5")));
    }

    /**
     * Test the property 'vat'
     */
    @Test
    public void vatTest() {
        assertEquals(BigDecimal.valueOf(10), model.getVat());
        model.setVat(BigDecimal.valueOf(22));
        assertEquals(BigDecimal.valueOf(22), model.getVat());

        ReceivedDocumentInfoItemsDefaultValues i = model.vat(BigDecimal.valueOf(10));
        ReceivedDocumentInfoItemsDefaultValues expected = new ReceivedDocumentInfoItemsDefaultValues()
                .vat(BigDecimal.valueOf(10));
        assertEquals(expected, i);
    }

}
