name: Java SDK Validation

on:
  pull_request:
    branches: [ master ]

jobs:
  validate:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java: [8, 11, 16, 17]

    steps:
    - id: checkout
      name: Checkout repo
      uses: actions/checkout@v2

    - id: setup-jdk
      name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

    - id: executable-wrapper
      name: Gradle Wrapper is made executable
      run: |
        chmod a+x ./gradlew

    - id: gradle-build
      name: Build with Gradle
      run: |
        ./gradlew build

    - id: gradle-test
      name: Test with Gradle
      run: |
        ./gradlew test
